spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: tapwaterManagement
            username: iosys
            password: iosys
            authentication-database: tapwaterManagement