spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: tapreadManagement
            username: iosys
            password: iosys
            authentication-database: tapreadManagement
    kafka:
        bootstrap-servers: localhost:9092
        topic:
            tapReadPersisted: TAPREAD_PERSISTED_TOPIC
    security:
        basic:
            enabled: false
