spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/psnpsn/touchless-backend
                    search-paths: config-properties
                    clone-on-start: true
